import { useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Tailwind Practice</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<h1 className="text-center text-6xl">HomePage</h1>
		</div>
	);
}
